-- SEQUENCE
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE;

-- USER_DATA definition
-- Drop table
-- DROP TABLE USER_DATA;

CREATE TABLE USER_DATA (
	ID BIGINT NOT NULL,
	PASSWORD VARCHAR(50),
	USER_ROLE VARCHAR(10),
	USERNAME VARCHAR(50),
	TOKEN VARCHAR(100),
	CONSTRAINT CONSTRAINT_UD PRIMARY KEY (ID)
);

-- MESSAGE definition
-- Drop table
-- DROP TABLE MESSAGE;

CREATE TABLE MESSAGE (
	ID BIGINT NOT NULL,
	CONTENT VARCHAR(250),
	CREATION_DATE TIMESTAMP,
	USER_REF VARCHAR(50),
	CONSTRAINT CONSTRAINT_MS PRIMARY KEY (ID)
);